// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: hitsperf.proto

package hitsperf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *IncRequest) Reset() {
	*x = IncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hitsperf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncRequest) ProtoMessage() {}

func (x *IncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hitsperf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncRequest.ProtoReflect.Descriptor instead.
func (*IncRequest) Descriptor() ([]byte, []int) {
	return file_hitsperf_proto_rawDescGZIP(), []int{0}
}

func (x *IncRequest) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type IncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IncResponse) Reset() {
	*x = IncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hitsperf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncResponse) ProtoMessage() {}

func (x *IncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hitsperf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncResponse.ProtoReflect.Descriptor instead.
func (*IncResponse) Descriptor() ([]byte, []int) {
	return file_hitsperf_proto_rawDescGZIP(), []int{1}
}

type EventIncProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EventIncProto) Reset() {
	*x = EventIncProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hitsperf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventIncProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventIncProto) ProtoMessage() {}

func (x *EventIncProto) ProtoReflect() protoreflect.Message {
	mi := &file_hitsperf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventIncProto.ProtoReflect.Descriptor instead.
func (*EventIncProto) Descriptor() ([]byte, []int) {
	return file_hitsperf_proto_rawDescGZIP(), []int{2}
}

func (x *EventIncProto) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_hitsperf_proto protoreflect.FileDescriptor

var file_hitsperf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x69, 0x74, 0x73, 0x70, 0x65, 0x72, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x68, 0x69, 0x74, 0x73, 0x70, 0x65, 0x72, 0x66, 0x22, 0x22, 0x0a, 0x0a, 0x49, 0x6e,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0d,
	0x0a, 0x0b, 0x49, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a,
	0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0x45, 0x0a, 0x0f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x03, 0x49, 0x6e, 0x63, 0x12, 0x14,
	0x2e, 0x68, 0x69, 0x74, 0x73, 0x70, 0x65, 0x72, 0x66, 0x2e, 0x49, 0x6e, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x68, 0x69, 0x74, 0x73, 0x70, 0x65, 0x72, 0x66, 0x2e,
	0x49, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x3b, 0x68, 0x69, 0x74, 0x73, 0x70, 0x65, 0x72, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_hitsperf_proto_rawDescOnce sync.Once
	file_hitsperf_proto_rawDescData = file_hitsperf_proto_rawDesc
)

func file_hitsperf_proto_rawDescGZIP() []byte {
	file_hitsperf_proto_rawDescOnce.Do(func() {
		file_hitsperf_proto_rawDescData = protoimpl.X.CompressGZIP(file_hitsperf_proto_rawDescData)
	})
	return file_hitsperf_proto_rawDescData
}

var file_hitsperf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hitsperf_proto_goTypes = []interface{}{
	(*IncRequest)(nil),    // 0: hitsperf.IncRequest
	(*IncResponse)(nil),   // 1: hitsperf.IncResponse
	(*EventIncProto)(nil), // 2: hitsperf.EventIncProto
}
var file_hitsperf_proto_depIdxs = []int32{
	0, // 0: hitsperf.IncreaseService.Inc:input_type -> hitsperf.IncRequest
	1, // 1: hitsperf.IncreaseService.Inc:output_type -> hitsperf.IncResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hitsperf_proto_init() }
func file_hitsperf_proto_init() {
	if File_hitsperf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hitsperf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hitsperf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hitsperf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventIncProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hitsperf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hitsperf_proto_goTypes,
		DependencyIndexes: file_hitsperf_proto_depIdxs,
		MessageInfos:      file_hitsperf_proto_msgTypes,
	}.Build()
	File_hitsperf_proto = out.File
	file_hitsperf_proto_rawDesc = nil
	file_hitsperf_proto_goTypes = nil
	file_hitsperf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IncreaseServiceClient is the client API for IncreaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IncreaseServiceClient interface {
	Inc(ctx context.Context, in *IncRequest, opts ...grpc.CallOption) (*IncResponse, error)
}

type increaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIncreaseServiceClient(cc grpc.ClientConnInterface) IncreaseServiceClient {
	return &increaseServiceClient{cc}
}

func (c *increaseServiceClient) Inc(ctx context.Context, in *IncRequest, opts ...grpc.CallOption) (*IncResponse, error) {
	out := new(IncResponse)
	err := c.cc.Invoke(ctx, "/hitsperf.IncreaseService/Inc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncreaseServiceServer is the server API for IncreaseService service.
type IncreaseServiceServer interface {
	Inc(context.Context, *IncRequest) (*IncResponse, error)
}

// UnimplementedIncreaseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIncreaseServiceServer struct {
}

func (*UnimplementedIncreaseServiceServer) Inc(context.Context, *IncRequest) (*IncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inc not implemented")
}

func RegisterIncreaseServiceServer(s *grpc.Server, srv IncreaseServiceServer) {
	s.RegisterService(&_IncreaseService_serviceDesc, srv)
}

func _IncreaseService_Inc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncreaseServiceServer).Inc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hitsperf.IncreaseService/Inc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncreaseServiceServer).Inc(ctx, req.(*IncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IncreaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hitsperf.IncreaseService",
	HandlerType: (*IncreaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inc",
			Handler:    _IncreaseService_Inc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hitsperf.proto",
}
